# Use an official Python runtime as the base image
FROM python:3.10

# Set the working directory in the container
WORKDIR /app

# Copy the Python program files to the container
COPY . /app

# Install the required dependencies
RUN pip install -r requirements.txt

# Run the Python program
CMD ["python", "Trivia_Bot_V2.py"]

